platform:
  exposure:
    type: ingress
  ingress:
    className: nginx
    hosts:
      - host: ctf.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ret2shell-tls
        hosts:
          - ctf.example.com
  config:
    server:
      externalDomain: ctf.example.com

registry:
  mode: internal
  externalAccess:
    host: registry.example.com:30310
