//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use sea_orm::{
    entity::prelude::*, ActiveValue, IntoActiveModel, Iterable, QueryOrder, QuerySelect,
};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "announcement")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    pub publisher_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub pinned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::PublisherId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_announcement_by_id(
    conn: &DatabaseConnection, id: i64,
) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(conn).await
}

pub async fn get_announcement_page(
    conn: &DatabaseConnection, page: u64, per_page: u64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let paginator = Entity::find()
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content)))
        .order_by_desc(Column::Pinned)
        .order_by_desc(Column::PublishedAt)
        .into_model()
        .paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let announcements = paginator.fetch_page(page - 1).await?;
    Ok((announcements, num_pages))
}

pub async fn create_announcement(
    conn: &DatabaseConnection, announcement: Model,
) -> Result<Model, DbErr> {
    let mut active_model: ActiveModel = announcement.into();
    active_model.id = ActiveValue::NotSet;
    active_model.published_at = ActiveValue::Set(Utc::now());
    active_model.updated_at = ActiveValue::Set(Utc::now());
    active_model.insert(conn).await
}

pub async fn update_announcement(
    conn: &DatabaseConnection, id: i64, announcement: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::Unchanged(id),
        updated_at: ActiveValue::Set(Utc::now()),
        published_at: ActiveValue::Unchanged(announcement.published_at),
        ..announcement.into_active_model().reset_all()
    };
    active_model.update(conn).await
}

pub async fn delete_announcement(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}
