//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "answer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub updated_at: DateTime<Utc>,
    pub author_id: Option<i64>,
    #[sea_orm(unique)]
    pub challenge_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_answer_by_challenge_id(
    conn: &DatabaseConnection,
    challenge_id: i64,
) -> Result<Option<Model>, DbErr> {
    let answer = Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id))
        .one(conn)
        .await?;
    Ok(answer)
}

pub async fn create_answer(
    conn: &DatabaseConnection,
    user_id: i64,
    challenge_id: i64,
    answer: Model,
) -> Result<Model, DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        published_at: ActiveValue::Set(Utc::now()),
        updated_at: ActiveValue::Set(Utc::now()),
        author_id: ActiveValue::Set(Some(user_id)),
        challenge_id: ActiveValue::Set(challenge_id),
        ..answer.into_active_model().reset_all()
    };
    active_model.insert(conn).await
}

pub async fn update_answer(
    conn: &DatabaseConnection,
    user_id: i64,
    challenge_id: i64,
    answer: Model,
) -> Result<Model, DbErr> {
    match get_answer_by_challenge_id(conn, challenge_id).await? {
        Some(old_answer) => {
            let active_model = ActiveModel {
                id: ActiveValue::set(old_answer.id),
                challenge_id: ActiveValue::Unchanged(challenge_id),
                published_at: ActiveValue::NotSet,
                updated_at: ActiveValue::Set(Utc::now()),
                author_id: ActiveValue::Set(Some(user_id)),
                ..answer.into_active_model().reset_all()
            };
            active_model.update(conn).await
        }
        None => return Err(DbErr::RecordNotFound("answer".to_string())),
    }
}

pub async fn delete_answer_by_challenge_id(
    conn: &DatabaseConnection,
    challenge_id: i64,
) -> Result<(), DbErr> {
    match get_answer_by_challenge_id(conn, challenge_id).await {
        Ok(Some(answer)) => Entity::delete_by_id(answer.id).exec(conn).await.map(|_| ()),
        Ok(None) => Err(DbErr::RecordNotFound("answer".to_string())),
        Err(e) => Err(e),
    }
}
