//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub challenge_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create_hint(
    conn: &DatabaseConnection, challenge_id: i64, hint: Model,
) -> Result<(), DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        challenge_id: ActiveValue::Set(challenge_id),
        created_at: ActiveValue::Set(Utc::now()),
        content: ActiveValue::Set(hint.content),
    };
    active_model.insert(conn).await.map(|_| ())
}

pub async fn delete_hint(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(conn).await.map(|_| ())
}

pub async fn get_hint_list(
    conn: &DatabaseConnection, challenge_id: i64,
) -> Result<Vec<Model>, DbErr> {
    let hints = Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id))
        .all(conn)
        .await?;
    Ok(hints)
}
