//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel, QueryOrder};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    pub game_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create_notification(
    conn: &DatabaseConnection, game_id: i64, notification: Model,
) -> Result<(), DbErr> {
    let active_model = ActiveModel {
        id: ActiveValue::NotSet,
        published_at: ActiveValue::Set(Utc::now()),
        game_id: ActiveValue::Set(game_id),
        ..notification.into_active_model().reset_all()
    };
    active_model.insert(conn).await.map(|_| ())
}

pub async fn get_notification_page(
    conn: &DatabaseConnection, page: u64, per_page: u64, game_id: i64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let sql = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .order_by_desc(Column::PublishedAt);
    let paginator = sql.into_model().paginate(conn, per_page);
    let num_pages = paginator.num_pages().await?;
    let notifications: Vec<Model> = paginator.fetch_page(page - 1).await?;
    Ok((notifications, num_pages))
}

pub async fn delete_notification(conn: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    let notification = Entity::find_by_id(id).one(conn).await?;
    match notification {
        Some(notification) => notification.delete(conn).await.map(|_| ()),
        None => Err(DbErr::RecordNotFound("notification".to_string())),
    }
}
