//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{QuerySelect, FromQueryResult, QueryOrder};
use sea_orm::entity::prelude::*;

use chrono::serde::ts_seconds::{deserialize as from_ts, serialize as to_ts};
use chrono::{DateTime, Utc};
use sea_query::JoinType;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub created_at: DateTime<Utc>,
    pub user_id: i64,
    pub challenge_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub solved: bool,
    pub with_score: bool,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ModelWithUserAndChallengeInfo {
    pub id: i64,
    pub created_at: chrono::DateTime<Utc>,
    pub user_id: i64,
    pub challenge_id: i64,
    pub game_id: i64,
    pub content: String,
    pub solved: bool,
    pub user_name: String,
    pub challenge_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_submission_page(
    conn: &DatabaseConnection,
    challenge_id: i64,
    page: u64,
    per_page: u64
) -> Result<(Vec<ModelWithUserAndChallengeInfo>, u64), DbErr> {
    let mut sql = Entity::find()
        .filter(Column::ChallengeId.eq(challenge_id));
    sql = sql
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def());
    let sql = sql
        .column_as(super::challenge::Column::Name, "challenge_name")
        .column_as(super::user::Column::Name, "user_name")
        .column_as(super::challenge::Column::GameId, "game_id")
        .order_by_desc(Column::CreatedAt)
        .into_model::<ModelWithUserAndChallengeInfo>();
    let paginator = sql.paginate(conn, per_page);
    let resp = paginator.fetch_page(page - 1).await?;
    let num_pages = paginator.num_pages().await?;
    Ok((resp, num_pages))
}