//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::{entity::prelude::*, ActiveValue};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user2_team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub team_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Team,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn link_team_user(
    conn: &DatabaseConnection, user_id: i64, team_id: i64,
) -> Result<(), DbErr> {
    let res = Entity::find()
        .filter(Column::UserId.eq(user_id).and(Column::TeamId.eq(team_id)))
        .one(conn)
        .await?;
    if res.is_none() {
        let res = ActiveModel {
            id: ActiveValue::NotSet,
            user_id: ActiveValue::Set(user_id),
            team_id: ActiveValue::Set(team_id),
        };
        res.insert(conn).await?;
    }
    Ok(())
}

pub async fn get_team_size(conn: &DatabaseConnection, team_id: i64) -> Result<u64, DbErr> {
    let res = Entity::find()
        .filter(Column::TeamId.eq(team_id))
        .count(conn)
        .await?;
    Ok(res)
}
