apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ret2shell.challengeNamespace" . }}
  labels:
    {{- include "ret2shell.commonLabels" . | nindent 4 }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internet-disabled
  namespace: {{ include "ret2shell.challengeNamespace" . }}
  labels:
    {{- include "ret2shell.commonLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      ret.sh.cn/internet: "false"
  policyTypes:
    - Egress
