const { addDynamicIconSelectors } = require('@iconify/tailwind')
const typography = require('@tailwindcss/typography')
const daisyui = require('daisyui')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    fontFamily: {
      sans: [
        '"JetBrains Mono"',
        'Menlo',
        '-apple-system',
        '"Noto Sans"',
        '"Helvetica Neue"',
        'Helvetica',
        '"Nimbus Sans L"',
        'Arial',
        '"Liberation Sans"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Noto Sans CJK SC"',
        '"Source Han Sans SC"',
        '"Source Han Sans CN"',
        '"Microsoft YaHei"',
        'Consolas',
        'Courier',
        'monospace',
      ],
      serif: [
        '"JetBrains Mono"',
        'Menlo',
        '-apple-system',
        '"Noto Sans"',
        '"Helvetica Neue"',
        'Helvetica',
        '"Nimbus Sans L"',
        'Arial',
        '"Liberation Sans"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Noto Sans CJK SC"',
        '"Source Han Sans SC"',
        '"Source Han Sans CN"',
        '"Microsoft YaHei"',
        'Consolas',
        'Courier',
        'monospace',
      ],
      mono: [
        '"JetBrains Mono"',
        'Menlo',
        '-apple-system',
        '"Noto Sans"',
        '"Helvetica Neue"',
        'Helvetica',
        '"Nimbus Sans L"',
        'Arial',
        '"Liberation Sans"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Noto Sans CJK SC"',
        '"Source Han Sans SC"',
        '"Source Han Sans CN"',
        '"Microsoft YaHei"',
        'Consolas',
        'Courier',
        'monospace',
      ],
      display: [
        '"JetBrains Mono"',
        'Menlo',
        '-apple-system',
        '"Noto Sans"',
        '"Helvetica Neue"',
        'Helvetica',
        '"Nimbus Sans L"',
        'Arial',
        '"Liberation Sans"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Noto Sans CJK SC"',
        '"Source Han Sans SC"',
        '"Source Han Sans CN"',
        '"Microsoft YaHei"',
        'Consolas',
        'Courier',
        'monospace',
      ],
      body: [
        '"JetBrains Mono"',
        'Menlo',
        '-apple-system',
        '"Noto Sans"',
        '"Helvetica Neue"',
        'Helvetica',
        '"Nimbus Sans L"',
        'Arial',
        '"Liberation Sans"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Noto Sans CJK SC"',
        '"Source Han Sans SC"',
        '"Source Han Sans CN"',
        '"Microsoft YaHei"',
        'Consolas',
        'Courier',
        'monospace',
      ],
    },
    extend: {},
  },
  plugins: [typography, daisyui, addDynamicIconSelectors()],
  daisyui: {
    styled: true,
    themes: [
      {
        dark: {
          primary: '#3399FF',
          secondary: '#60a5fa',
          accent: '#1FB2A6',
          neutral: '#202020',
          'base-100': '#121212',
          info: '#3399FF',
          success: '#36D399',
          warning: '#FBBD23',
          error: '#F83030',
        },
        light: {
          primary: '#0078D6',
          secondary: '#60a5fa',
          accent: '#1FB2A6',
          neutral: '#F0F0F0',
          'base-100': '#FFFFFF',
          info: '#0078D6',
          success: '#36AA3A',
          warning: '#ca9f00',
          error: '#F83030',
        },
      },
    ],
    base: true,
    utils: true,
    logs: false,
    rtl: false,
  },
}
